### ISSUE TITLE
Update structure for storybook

### ISSUE THREAD

**Issue by saltict** [Koniverse/SubWallet-React-UI#11]
## Todo
- [x] Update favicon
- [x] Update logo
- [x] Update Intro page
- [x] Create base theme preview structure
- [x] Publish theme preview with github page
- [x] Fix global style issues
